- menu_name: "เมนูภายใน"

- name: "งานการศึกษา"
  url: "/academic/"
  title: ""

- name: "งานวิจัย"
  url: "/documentation/"
  title: ""

- name: "กิจกรรมทั่วไป"
  url: "/activities/"
  title: ""

- name: "Blog"
  url: "/blog/"
  title: ""
